README.md

docs: added quick start guide #19

---

README.md

fixes #32
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieHubLive/pull/33"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: screenshot added

---

package-lock.json
src/App.js

fixes #28 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieHubLive/pull/34"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix : Sidebar Height

---

src/App.js

Closes #31 
removed duplicate entries from events-list for Map only 
so there will be single pic for all entries of same user on Map
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieHubLive/pull/37"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: multiple pics for same user on map

---

public/index.html

Changed meta description of the page from “created using  react app” to something more meaningful.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieHubLive/pull/50"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Update meta description 

---

.env
src/components/map.js
src/components/version.js
src/package.alias.json

Display deployed version in upper right corner of the map.
Closes #44 
My prettier settings are different.
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieHubLive/pull/48"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Feat: display deployed version

---

package-lock.json
src/components/event-card.js
src/index.css
tailwind.config.js

Rough suggestion for updating the event cards
- added a new off-white for the background
- changed tailwind config to pick this new value up
- adjusted the card

New Card Style

---

README.md

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieHubLive/pull/62"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

updated readme with data feed instructions

---

package-lock.json
package.json
src/components/map.js

Closes #16 
Added leaflet marker cluster, wrapped marker output in cluster.  Note this was only tested with test data json and needs to be tested with live diverse data as events come in
test data BEFORE cluster applied
After cluster added
marker cluster on click (zooms in to marker area)
Here is the test data I used in applying this feature for reference: 
[TestData.txt](https://github.com/EddieHubCommunity/EddieHubLive/files/10148706/TestData.txt)

Add leaflet marker cluster

---

src/components/convert-time.js
src/components/event-card.js

Closes #41 
Updated cards to include time - date not included as all data is from the same session/day 
<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/EddieHubLive/pull/57"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add time to event list

---

.github/workflows/deploy.yml
.github/workflows/kubescape.yml
.gitpod.yml
.husky/pre-commit
.prettierrc
CHANGELOG.md
README.md
package-lock.json
package.json
postcss.config.js
src/App.js
src/components/event-card.js
src/components/map.js
src/components/version.js
src/index.css
src/index.js

Add Prettier

---

src/components/map.js
src/components/zoom-to-marker.js

Closes #66 
This will add a zoom to feature on each new event to highlight contributors
Another ticket will be opened to refine this feature to consider marker state and only zoom in on new to the map users
This feature will need testing in a live environment to see how it handles new events coming in and the pacing.
Short video of the feature in action
https://user-images.githubusercontent.com/97615019/206065582-2c7bcf7d-dd7c-4850-8feb-44afa2c09929.mov
Needs to be tested with more events coming in at the expected live stream pace and likely refined based on that info

Feature zoom to marker

---

CONTRIBUTING.md
README.md

Added a basic contribution guide and moved up "how to trigger data" section in readme to make it more discorverable

Add contributor guide and update readme

---

.github/workflows/build.yml

ci: build action

---

package-lock.json
package.json
src/App.jsx
src/components/event-card.jsx
src/components/map.jsx
src/components/marker-cluster.jsx

Closes #82 
fixed conflicting version of marker cluster
fixed errors in proptypes in eventcard and map

Bugfix leaflet markercluster

---

LICENSE.md

Closes #59.
- Add the MIT license.

docs: add the MIT license

---

src/App.jsx
src/components/event-card.jsx

Closes #85 
Closes #63 
adjusted ids and useEffect as the render was overwriting previous data. This change fixed the duplicate issues bug seen in an earlier issue as well

dependency array for useeffect

---

src/App.jsx
src/components/map.jsx

Closes #79 
There were multiple css classes calling h-screen that needed to be adjusted causing the unwanted scroll

fix vertical height scroll issue

---

src/App.jsx
src/index.css

Closes  #99  
When the events list overflows, the scrollbar is added to the parent element of the events list, and the map, I have now hidden the overflow and added custom styling to the scrollbar for the events list.

Fixed vertical overflow on whole screen and added scroll bar styling and 

---

src/components/event-card.jsx
tailwind.config.cjs

#88 
Closes #88 
Changes are done in the (event-card.jsx) and (tailwind config js) file to make the UI responsive.
In the tailwind config file custom screen config was added for screens under 895 px the div will be flex-column.
And according to config, classes added to the event card file 
Changes are made according to style or order of project no extra thing are added✨

[UI] Responsiveness of UI 

---

src/components/event-card.jsx
src/components/map.jsx

Closes #107 
I have added check for location in event card and filtered out all the events with location data to be shown on the map.

Adding Validation for Location Data
